"""Utilities for loading and aligning multi-participant experiment data.

This module focuses on log files generated by ParticipantTest sessions under:
  logs/P###/S##/

Supported files per session:
- session_manifest.json
- segments.csv
- events.jsonl
- outcomes_flat.csv (optional)
- eye_events.csv (optional)

Typical workflow:
1) Discover all sessions under logs/
2) Load selected tables into pandas DataFrames
3) Align participant/session metrics for statistics
4) Export NumPy arrays for modeling
"""

from __future__ import annotations

from dataclasses import dataclass
import json
from pathlib import Path
from typing import Any, Iterable, Sequence

import numpy as np
import pandas as pd


@dataclass(frozen=True)
class SessionPaths:
    """File locations for one participant session."""

    participant_id: str
    session_id: str
    session_dir: Path
    session_manifest: Path | None
    segments_csv: Path | None
    events_jsonl: Path | None
    outcomes_flat_csv: Path | None
    eye_events_csv: Path | None


def discover_sessions(logs_root: str | Path = "logs") -> list[SessionPaths]:
    """Discover participant session folders and known files.

    Args:
        logs_root: Root directory that contains P### folders.

    Returns:
        A sorted list of SessionPaths records.
    """
    root = Path(logs_root)
    if not root.exists():
        return []

    sessions: list[SessionPaths] = []
    for participant_dir in sorted(p for p in root.iterdir() if p.is_dir() and p.name.startswith("P")):
        for session_dir in sorted(s for s in participant_dir.iterdir() if s.is_dir() and s.name.startswith("S")):
            sessions.append(
                SessionPaths(
                    participant_id=participant_dir.name,
                    session_id=session_dir.name,
                    session_dir=session_dir,
                    session_manifest=_optional_file(session_dir / "session_manifest.json"),
                    segments_csv=_optional_file(session_dir / "segments.csv"),
                    events_jsonl=_optional_file(session_dir / "events.jsonl"),
                    outcomes_flat_csv=_optional_file(session_dir / "outcomes_flat.csv"),
                    eye_events_csv=_optional_file(session_dir / "eye_events.csv"),
                )
            )
    return sessions


def load_session_index(logs_root: str | Path = "logs") -> pd.DataFrame:
    """Return a tabular index of discovered session files."""
    records = []
    for s in discover_sessions(logs_root):
        records.append(
            {
                "participant_id": s.participant_id,
                "session_id": s.session_id,
                "session_dir": str(s.session_dir),
                "session_manifest": _path_or_none(s.session_manifest),
                "segments_csv": _path_or_none(s.segments_csv),
                "events_jsonl": _path_or_none(s.events_jsonl),
                "outcomes_flat_csv": _path_or_none(s.outcomes_flat_csv),
                "eye_events_csv": _path_or_none(s.eye_events_csv),
            }
        )
    return pd.DataFrame.from_records(records)


def load_segments(sessions: Sequence[SessionPaths] | None = None, logs_root: str | Path = "logs") -> pd.DataFrame:
    """Load and concatenate all segments.csv files."""
    sessions = list(sessions) if sessions is not None else discover_sessions(logs_root)
    frames: list[pd.DataFrame] = []

    for s in sessions:
        if s.segments_csv is None:
            continue
        df = pd.read_csv(s.segments_csv)
        df.insert(0, "participant_id", s.participant_id)
        df.insert(1, "session_id", s.session_id)
        frames.append(df)

    return pd.concat(frames, ignore_index=True) if frames else pd.DataFrame()


def load_events(sessions: Sequence[SessionPaths] | None = None, logs_root: str | Path = "logs") -> pd.DataFrame:
    """Load and concatenate all events.jsonl files as a flat table.

    The event payload is normalized into columns with prefix payload_.
    """
    sessions = list(sessions) if sessions is not None else discover_sessions(logs_root)
    rows: list[dict[str, Any]] = []

    for s in sessions:
        if s.events_jsonl is None:
            continue
        with s.events_jsonl.open("r", encoding="utf-8") as fh:
            for line in fh:
                line = line.strip()
                if not line:
                    continue
                item = json.loads(line)
                payload = item.get("payload", {})
                flat_payload = {f"payload_{k}": v for k, v in payload.items()} if isinstance(payload, dict) else {}
                rows.append(
                    {
                        "participant_id": s.participant_id,
                        "session_id": s.session_id,
                        "event_type": item.get("event_type"),
                        "timestamp_utc": item.get("timestamp_utc"),
                        **flat_payload,
                    }
                )

    return pd.DataFrame.from_records(rows)


def load_eye_events(sessions: Sequence[SessionPaths] | None = None, logs_root: str | Path = "logs") -> pd.DataFrame:
    """Load and concatenate all eye_events.csv files, if present."""
    sessions = list(sessions) if sessions is not None else discover_sessions(logs_root)
    frames: list[pd.DataFrame] = []

    for s in sessions:
        if s.eye_events_csv is None:
            continue
        df = pd.read_csv(s.eye_events_csv)
        df.insert(0, "participant_id", s.participant_id)
        df.insert(1, "session_id", s.session_id)
        frames.append(df)

    return pd.concat(frames, ignore_index=True) if frames else pd.DataFrame()


def load_outcomes_flat(sessions: Sequence[SessionPaths] | None = None, logs_root: str | Path = "logs") -> pd.DataFrame:
    """Load one-row-per-session outcomes table.

    If outcomes_flat.csv is missing for a session, this function falls back to
    flattening the outcomes section in session_manifest.json.
    """
    sessions = list(sessions) if sessions is not None else discover_sessions(logs_root)
    frames: list[pd.DataFrame] = []

    for s in sessions:
        if s.outcomes_flat_csv is not None:
            df = pd.read_csv(s.outcomes_flat_csv)
            if "participant_id" not in df.columns:
                df.insert(0, "participant_id", s.participant_id)
            if "session_id" not in df.columns:
                df.insert(1, "session_id", s.session_id)
            frames.append(df)
            continue

        if s.session_manifest is None:
            continue

        fallback = _manifest_outcomes_to_row(s.session_manifest)
        if fallback is None:
            continue

        fallback["participant_id"] = s.participant_id
        fallback["session_id"] = s.session_id
        frames.append(pd.DataFrame([fallback]))

    return pd.concat(frames, ignore_index=True) if frames else pd.DataFrame()


def load_detectability_trials_from_events(events_df: pd.DataFrame | None = None, logs_root: str | Path = "logs") -> pd.DataFrame:
    """Extract detectability trial rows from events table.

    Output columns include condition, correctness, and rt_ms where available.
    """
    if events_df is None:
        events_df = load_events(logs_root=logs_root)
    if events_df.empty:
        return events_df

    mask = events_df["event_type"].eq("detectability_trial")
    cols = [
        "participant_id",
        "session_id",
        "timestamp_utc",
        "payload_phase",
        "payload_trial_index",
        "payload_trial_file",
        "payload_condition",
        "payload_selected_condition",
        "payload_is_correct",
        "payload_rt_ms",
    ]
    present = [c for c in cols if c in events_df.columns]
    out = events_df.loc[mask, present].copy()
    out = out.rename(
        columns={
            "payload_phase": "phase",
            "payload_trial_index": "trial_index",
            "payload_trial_file": "trial_file",
            "payload_condition": "condition",
            "payload_selected_condition": "selected_condition",
            "payload_is_correct": "is_correct",
            "payload_rt_ms": "rt_ms",
        }
    )
    return out


def summarize_detectability_by_condition(trials_df: pd.DataFrame) -> pd.DataFrame:
    """Summarize detectability accuracy and RT by participant/session/condition."""
    if trials_df.empty:
        return trials_df

    required = {"participant_id", "session_id", "condition", "is_correct", "rt_ms"}
    missing = required - set(trials_df.columns)
    if missing:
        raise ValueError(f"Missing required columns: {sorted(missing)}")

    work = trials_df.copy()
    work["is_correct"] = work["is_correct"].astype(float)
    work["rt_ms"] = pd.to_numeric(work["rt_ms"], errors="coerce")

    grouped = (
        work.groupby(["participant_id", "session_id", "condition"], dropna=False)
        .agg(
            n_trials=("is_correct", "size"),
            accuracy_pct=("is_correct", lambda s: float(s.mean() * 100.0)),
            mean_rt_ms=("rt_ms", "mean"),
            median_rt_ms=("rt_ms", "median"),
        )
        .reset_index()
    )
    return grouped


def align_sessions_long(
    outcomes_df: pd.DataFrame,
    detectability_condition_df: pd.DataFrame | None = None,
    eye_events_df: pd.DataFrame | None = None,
) -> pd.DataFrame:
    """Create a long aligned table keyed by participant_id/session_id.

    This keeps one row per participant/session/condition where condition-level
    metrics exist, and repeats session-level outcomes across conditions.
    """
    if outcomes_df.empty:
        return outcomes_df

    aligned = outcomes_df.copy()

    if detectability_condition_df is not None and not detectability_condition_df.empty:
        aligned = aligned.merge(
            detectability_condition_df,
            on=["participant_id", "session_id"],
            how="left",
            suffixes=("", "_detectability"),
        )

    if eye_events_df is not None and not eye_events_df.empty:
        eye_summary = summarize_eye_events_for_alignment(eye_events_df)
        aligned = aligned.merge(
            eye_summary,
            on=["participant_id", "session_id", "condition"],
            how="left",
            suffixes=("", "_eye"),
        )

    return aligned


def summarize_eye_events_for_alignment(eye_events_df: pd.DataFrame) -> pd.DataFrame:
    """Summarize eye event counts/duration by participant/session/condition/event_type."""
    if eye_events_df.empty:
        return eye_events_df

    needed = {"participant_id", "session_id", "condition", "event_type", "duration_ms"}
    missing = needed - set(eye_events_df.columns)
    if missing:
        raise ValueError(f"Missing required columns for eye summary: {sorted(missing)}")

    work = eye_events_df.copy()
    work["duration_ms"] = pd.to_numeric(work["duration_ms"], errors="coerce")

    grouped = (
        work.groupby(["participant_id", "session_id", "condition", "event_type"], dropna=False)
        .agg(event_count=("event_type", "size"), total_duration_ms=("duration_ms", "sum"))
        .reset_index()
    )

    pivot = grouped.pivot_table(
        index=["participant_id", "session_id", "condition"],
        columns="event_type",
        values=["event_count", "total_duration_ms"],
        fill_value=0.0,
    )

    pivot.columns = [f"{a}_{b}" for a, b in pivot.columns.to_flat_index()]
    return pivot.reset_index()


def to_numpy_matrix(
    df: pd.DataFrame,
    feature_columns: Sequence[str],
    *,
    dtype: np.dtype = np.float64,
    fillna: float | None = np.nan,
) -> tuple[np.ndarray, list[str]]:
    """Convert selected DataFrame columns to a NumPy design matrix.

    Returns:
        (X, used_columns)
    """
    missing = [c for c in feature_columns if c not in df.columns]
    if missing:
        raise ValueError(f"Columns not found in DataFrame: {missing}")

    work = df.loc[:, list(feature_columns)].copy()
    for col in work.columns:
        work[col] = pd.to_numeric(work[col], errors="coerce")

    if fillna is not None:
        work = work.fillna(fillna)

    return work.to_numpy(dtype=dtype), list(work.columns)


def align_wide_by_condition(
    condition_df: pd.DataFrame,
    value_columns: Sequence[str],
    *,
    condition_column: str = "condition",
) -> pd.DataFrame:
    """Pivot long condition metrics into wide columns for each condition.

    Example output columns:
    - accuracy_pct_none
    - accuracy_pct_full
    - accuracy_pct_eyetracked
    """
    required = {"participant_id", "session_id", condition_column, *value_columns}
    missing = required - set(condition_df.columns)
    if missing:
        raise ValueError(f"Missing required columns: {sorted(missing)}")

    pivot = condition_df.pivot_table(
        index=["participant_id", "session_id"],
        columns=condition_column,
        values=list(value_columns),
        aggfunc="first",
    )
    pivot.columns = [f"{metric}_{cond}" for metric, cond in pivot.columns.to_flat_index()]
    return pivot.reset_index()


def _manifest_outcomes_to_row(manifest_path: Path) -> dict[str, Any] | None:
    try:
        data = json.loads(manifest_path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return None

    outcomes = data.get("outcomes")
    if not isinstance(outcomes, dict):
        return None

    row: dict[str, Any] = {}
    for variable, item in outcomes.items():
        if not isinstance(item, dict):
            continue

        value = item.get("value")
        status = item.get("status")
        source = item.get("source")

        row[f"{variable}__status"] = status
        row[f"{variable}__source"] = source

        if isinstance(value, (dict, list)):
            for k, v in _flatten_json(value, prefix=f"{variable}__value").items():
                row[k] = v
        else:
            row[f"{variable}__value"] = value

    return row


def _flatten_json(obj: Any, *, prefix: str = "") -> dict[str, Any]:
    """Flatten nested dict/list structures using __ as separator."""
    out: dict[str, Any] = {}

    if isinstance(obj, dict):
        for key, value in obj.items():
            next_prefix = f"{prefix}__{key}" if prefix else str(key)
            out.update(_flatten_json(value, prefix=next_prefix))
        return out

    if isinstance(obj, list):
        for idx, value in enumerate(obj):
            next_prefix = f"{prefix}__{idx}"
            out.update(_flatten_json(value, prefix=next_prefix))
        return out

    out[prefix] = obj
    return out


def _optional_file(path: Path) -> Path | None:
    return path if path.exists() else None


def _path_or_none(path: Path | None) -> str | None:
    return str(path) if path is not None else None
